Repository honeycombio/honeyvent, pull requests merged in 2021-11, with the labels that each got.

#41 --no-tls-verify
  main.go
Labels: type: enhancement, version: bump minor

#42 Bump libhoney-go to v1.15.6
  go.mod
  go.sum
  vendor/github.com/honeycombio/libhoney-go/CHANGELOG.md
  vendor/github.com/honeycombio/libhoney-go/README.md
  vendor/github.com/honeycombio/libhoney-go/libhoney.go
  vendor/github.com/honeycombio/libhoney-go/transmission/transmission.go
  vendor/modules.txt
Labels: version: bump patch, type: maintenance

#43 Prepare v1.1.0 release
  CHANGELOG.md
  RELEASE.md
Labels: version: no bump, type: maintenance

#44 Create draft github release on publish
  .circleci/config.yml
Labels: version: no bump, type: maintenance

#45 Update dependabot to monthly
  .github/dependabot.yml
Labels: version: no bump, type: maintenance, merge at will
